version: 2.1
jobs:
  one:
    docker:
      - image: node:8.16-buster
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
    steps:
      - run: pwd
      - run: ls -la
      - checkout
      - run:
          name: Install MySQL client
          command: apt-get update && apt-get install -y default-mysql-client
  two:
    docker:
      - image: node:8.16
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 10

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
